### ISSUE TITLE
Nullsafety

### ISSUE THREAD

**Issue by krjw-eyev** [Vanethos/minimize_app_plugin#3]
Is this going to be updated to null safety?

**Comment by Vanethos** [comment]
yes! @iberatkaya did it here:

https://github.com/Vanethos/minimize_app_plugin/pull/4

will update the lib asap

**Comment by prajwal27** [comment]
@Vanethos  when will it be released publicly?

**Comment by Vanethos** [comment]
Now! :D 

v 1.0.0-nullsafety.0 released!

**Comment by rodrigomoretto** [comment]
How should we write on pubspec.yaml, when I try "minimize_app: ˆ1.0.0-nullsafety.0" or "minimize_app: ˆ1.0.0-nullsafety" I get the following error:
`
Because MyApp depends on minimize_app ^1.0.0-nullsafety.0 which doesn't match any versions, version solving failed.
`
`
Because MyApp depends on minimize_app ^1.0.0-nullsafety which doesn't match any versions, version solving failed.
`

Also this new version doesn't seem to be available on pub.dev
